-- LOCF_USER 로 접속한 상태에서 실행한다.
-- 예시:
-- sqlplus LOCF_USER/비밀번호@//127.0.0.1:1521/XEPDB1

BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOCF_RESULT_SUMMARY CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOCF_RESULT_HDR CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOCF_AMORTIZATION_DTL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOCF_EIR_RESULT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOCF_CASHFLOW_BASE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOCF_TARGET_CONTRACT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOCF_BATCH_STEP_EXECUTION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOCF_BATCH_EXECUTION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOAN_BALANCE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOAN_REPAYMENT_SCHEDULE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOAN_RATE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOAN_CONTRACT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER_MASTER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_LOCF_RESULT_SUMMARY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_LOCF_RESULT_HDR'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_LOCF_AMORTIZATION_DTL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_LOCF_EIR_RESULT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_LOCF_CASHFLOW_BASE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_LOCF_TARGET_CONTRACT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_LOCF_BATCH_STEP_EXECUTION'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_LOCF_BATCH_EXECUTION'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_LOAN_BALANCE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_LOAN_REPAYMENT_SCHEDULE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_LOAN_RATE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_LOAN_CONTRACT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CUSTOMER_MASTER'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_LOCF_INSERT_RESULT_SUMMARY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_LOCF_INSERT_TARGET_CONTRACTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_LOCF_CLEAR_BATCH_DATA'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/

CREATE TABLE CUSTOMER_MASTER (
    CUSTOMER_ID NUMBER(19, 0) PRIMARY KEY,
    CUSTOMER_NO VARCHAR2(30 CHAR) NOT NULL UNIQUE,
    CUSTOMER_NAME VARCHAR2(100 CHAR) NOT NULL,
    CUSTOMER_TYPE VARCHAR2(20 CHAR) NOT NULL,
    SEGMENT_CODE VARCHAR2(20 CHAR),
    STATUS_CODE VARCHAR2(20 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NOT NULL
);

CREATE TABLE LOAN_CONTRACT (
    CONTRACT_ID NUMBER(19, 0) PRIMARY KEY,
    CONTRACT_NO VARCHAR2(30 CHAR) NOT NULL UNIQUE,
    CUSTOMER_ID NUMBER(19, 0) NOT NULL,
    PRODUCT_CODE VARCHAR2(30 CHAR) NOT NULL,
    LOAN_TYPE_CODE VARCHAR2(20 CHAR) NOT NULL,
    REPAYMENT_TYPE VARCHAR2(20 CHAR) NOT NULL,
    EXECUTION_DATE DATE NOT NULL,
    MATURITY_DATE DATE NOT NULL,
    PRINCIPAL_AMT NUMBER(18, 2) NOT NULL,
    FEE_AMT NUMBER(18, 2) NOT NULL,
    DIRECT_COST_AMT NUMBER(18, 2) NOT NULL,
    STATUS_CODE VARCHAR2(20 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT FK_LOAN_CONTRACT_01 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_MASTER (CUSTOMER_ID)
);

CREATE TABLE LOAN_RATE (
    RATE_ID NUMBER(19, 0) PRIMARY KEY,
    CONTRACT_ID NUMBER(19, 0) NOT NULL,
    RATE_TYPE VARCHAR2(20 CHAR) NOT NULL,
    ANNUAL_NOMINAL_RATE NUMBER(18, 10) NOT NULL,
    EFFECTIVE_FROM DATE NOT NULL,
    EFFECTIVE_TO DATE,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT FK_LOAN_RATE_01 FOREIGN KEY (CONTRACT_ID) REFERENCES LOAN_CONTRACT (CONTRACT_ID)
);

CREATE TABLE LOAN_REPAYMENT_SCHEDULE (
    SCHEDULE_ID NUMBER(19, 0) PRIMARY KEY,
    CONTRACT_ID NUMBER(19, 0) NOT NULL,
    INSTALLMENT_NO NUMBER(6, 0) NOT NULL,
    PAYMENT_DATE DATE NOT NULL,
    SCHEDULED_PAYMENT_AMT NUMBER(18, 2) NOT NULL,
    SCHEDULED_PRINCIPAL_AMT NUMBER(18, 2) NOT NULL,
    SCHEDULED_INTEREST_AMT NUMBER(18, 2) NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT FK_LOAN_REPAYMENT_SCHEDULE_01 FOREIGN KEY (CONTRACT_ID) REFERENCES LOAN_CONTRACT (CONTRACT_ID)
);

CREATE TABLE LOAN_BALANCE (
    BALANCE_ID NUMBER(19, 0) PRIMARY KEY,
    CONTRACT_ID NUMBER(19, 0) NOT NULL,
    BASE_DATE DATE NOT NULL,
    OUTSTANDING_PRINCIPAL_AMT NUMBER(18, 2) NOT NULL,
    ACCRUED_INTEREST_AMT NUMBER(18, 2) NOT NULL,
    STATUS_CODE VARCHAR2(20 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT FK_LOAN_BALANCE_01 FOREIGN KEY (CONTRACT_ID) REFERENCES LOAN_CONTRACT (CONTRACT_ID)
);

CREATE TABLE LOCF_BATCH_EXECUTION (
    BATCH_EXECUTION_ID NUMBER(19, 0) PRIMARY KEY,
    BATCH_RUN_NO VARCHAR2(40 CHAR) NOT NULL UNIQUE,
    BASE_DATE DATE NOT NULL,
    BATCH_TYPE VARCHAR2(20 CHAR) NOT NULL,
    STATUS_CODE VARCHAR2(20 CHAR) NOT NULL,
    TARGET_COUNT NUMBER(12, 0) NOT NULL,
    PROCESSED_COUNT NUMBER(12, 0) NOT NULL,
    ERROR_COUNT NUMBER(12, 0) NOT NULL,
    STARTED_AT TIMESTAMP(6) NOT NULL,
    FINISHED_AT TIMESTAMP(6),
    ERROR_MESSAGE VARCHAR2(1000 CHAR)
);

CREATE TABLE LOCF_BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID NUMBER(19, 0) PRIMARY KEY,
    BATCH_EXECUTION_ID NUMBER(19, 0) NOT NULL,
    STEP_NAME VARCHAR2(50 CHAR) NOT NULL,
    STATUS_CODE VARCHAR2(20 CHAR) NOT NULL,
    STARTED_AT TIMESTAMP(6) NOT NULL,
    FINISHED_AT TIMESTAMP(6),
    PROCESSED_COUNT NUMBER(12, 0) NOT NULL,
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    CONSTRAINT FK_LOCF_STEP_EXEC_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES LOCF_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE LOCF_TARGET_CONTRACT (
    TARGET_ID NUMBER(19, 0) PRIMARY KEY,
    BATCH_EXECUTION_ID NUMBER(19, 0) NOT NULL,
    CONTRACT_ID NUMBER(19, 0) NOT NULL,
    CONTRACT_NO VARCHAR2(30 CHAR) NOT NULL,
    CUSTOMER_ID NUMBER(19, 0) NOT NULL,
    PRODUCT_CODE VARCHAR2(30 CHAR) NOT NULL,
    REPAYMENT_TYPE VARCHAR2(20 CHAR) NOT NULL,
    PRINCIPAL_AMT NUMBER(18, 2) NOT NULL,
    FEE_AMT NUMBER(18, 2) NOT NULL,
    DIRECT_COST_AMT NUMBER(18, 2) NOT NULL,
    ANNUAL_NOMINAL_RATE NUMBER(18, 10) NOT NULL,
    EXECUTION_DATE DATE NOT NULL,
    MATURITY_DATE DATE NOT NULL,
    TERM_IN_MONTHS NUMBER(6, 0) NOT NULL,
    CONSTRAINT FK_LOCF_TARGET_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES LOCF_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE LOCF_CASHFLOW_BASE (
    CASHFLOW_BASE_ID NUMBER(19, 0) PRIMARY KEY,
    BATCH_EXECUTION_ID NUMBER(19, 0) NOT NULL,
    CONTRACT_ID NUMBER(19, 0) NOT NULL,
    CONTRACT_NO VARCHAR2(30 CHAR) NOT NULL,
    INSTALLMENT_NO NUMBER(6, 0) NOT NULL,
    PAYMENT_DATE DATE NOT NULL,
    SCHEDULED_PAYMENT_AMT NUMBER(18, 2) NOT NULL,
    SCHEDULED_PRINCIPAL_AMT NUMBER(18, 2) NOT NULL,
    SCHEDULED_INTEREST_AMT NUMBER(18, 2) NOT NULL,
    CONSTRAINT FK_LOCF_CF_BASE_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES LOCF_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE LOCF_EIR_RESULT (
    EIR_RESULT_ID NUMBER(19, 0) PRIMARY KEY,
    BATCH_EXECUTION_ID NUMBER(19, 0) NOT NULL,
    CONTRACT_ID NUMBER(19, 0) NOT NULL,
    CONTRACT_NO VARCHAR2(30 CHAR) NOT NULL,
    INITIAL_CARRYING_AMOUNT NUMBER(18, 2) NOT NULL,
    MONTHLY_EIR NUMBER(18, 10) NOT NULL,
    ANNUAL_EIR NUMBER(18, 10) NOT NULL,
    CONSTRAINT FK_LOCF_EIR_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES LOCF_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE LOCF_AMORTIZATION_DTL (
    AMORTIZATION_DTL_ID NUMBER(19, 0) PRIMARY KEY,
    BATCH_EXECUTION_ID NUMBER(19, 0) NOT NULL,
    CONTRACT_ID NUMBER(19, 0) NOT NULL,
    CONTRACT_NO VARCHAR2(30 CHAR) NOT NULL,
    INSTALLMENT_NO NUMBER(6, 0) NOT NULL,
    PAYMENT_DATE DATE NOT NULL,
    OPENING_PRINCIPAL_BAL NUMBER(18, 2) NOT NULL,
    OPENING_CARRYING_AMT NUMBER(18, 2) NOT NULL,
    SCHEDULED_PAYMENT_AMT NUMBER(18, 2) NOT NULL,
    SCHEDULED_PRINCIPAL_AMT NUMBER(18, 2) NOT NULL,
    SCHEDULED_INTEREST_AMT NUMBER(18, 2) NOT NULL,
    EFFECTIVE_INTEREST_REVENUE NUMBER(18, 2) NOT NULL,
    FEE_AMORTIZATION_AMT NUMBER(18, 2) NOT NULL,
    COST_AMORTIZATION_AMT NUMBER(18, 2) NOT NULL,
    NET_AMORTIZATION_AMT NUMBER(18, 2) NOT NULL,
    CLOSING_PRINCIPAL_BAL NUMBER(18, 2) NOT NULL,
    CLOSING_CARRYING_AMT NUMBER(18, 2) NOT NULL,
    CONSTRAINT FK_LOCF_AMORT_DTL_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES LOCF_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE LOCF_RESULT_HDR (
    RESULT_HDR_ID NUMBER(19, 0) PRIMARY KEY,
    BATCH_EXECUTION_ID NUMBER(19, 0) NOT NULL,
    BASE_DATE DATE NOT NULL,
    CONTRACT_ID NUMBER(19, 0) NOT NULL,
    CONTRACT_NO VARCHAR2(30 CHAR) NOT NULL,
    CUSTOMER_ID NUMBER(19, 0) NOT NULL,
    PRODUCT_CODE VARCHAR2(30 CHAR) NOT NULL,
    PRINCIPAL_AMT NUMBER(18, 2) NOT NULL,
    INITIAL_CARRYING_AMOUNT NUMBER(18, 2) NOT NULL,
    ANNUAL_EIR NUMBER(18, 10) NOT NULL,
    FINAL_CARRYING_AMOUNT NUMBER(18, 2) NOT NULL,
    TOTAL_EFFECTIVE_INTEREST_REV NUMBER(18, 2) NOT NULL,
    TOTAL_FEE_AMORTIZATION_AMT NUMBER(18, 2) NOT NULL,
    TOTAL_COST_AMORTIZATION_AMT NUMBER(18, 2) NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT FK_LOCF_RESULT_HDR_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES LOCF_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE LOCF_RESULT_SUMMARY (
    SUMMARY_ID NUMBER(19, 0) PRIMARY KEY,
    BATCH_EXECUTION_ID NUMBER(19, 0) NOT NULL,
    BASE_DATE DATE NOT NULL,
    PRODUCT_CODE VARCHAR2(30 CHAR) NOT NULL,
    CONTRACT_COUNT NUMBER(12, 0) NOT NULL,
    TOTAL_INITIAL_CARRYING_AMT NUMBER(18, 2) NOT NULL,
    TOTAL_FINAL_CARRYING_AMT NUMBER(18, 2) NOT NULL,
    TOTAL_EFFECTIVE_INTEREST_REV NUMBER(18, 2) NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT FK_LOCF_RESULT_SUM_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES LOCF_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE SEQUENCE SQ_LOCF_BATCH_EXECUTION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_LOCF_BATCH_STEP_EXECUTION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_LOCF_TARGET_CONTRACT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_LOCF_CASHFLOW_BASE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_LOCF_EIR_RESULT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_LOCF_AMORTIZATION_DTL START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_LOCF_RESULT_HDR START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_LOCF_RESULT_SUMMARY START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_CUSTOMER_MASTER START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_LOAN_CONTRACT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_LOAN_RATE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_LOAN_REPAYMENT_SCHEDULE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_LOAN_BALANCE START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE PROCEDURE PRC_LOCF_CLEAR_BATCH_DATA (
    p_batch_execution_id IN NUMBER
) IS
BEGIN
    DELETE FROM LOCF_RESULT_SUMMARY
     WHERE BATCH_EXECUTION_ID = p_batch_execution_id;

    DELETE FROM LOCF_RESULT_HDR
     WHERE BATCH_EXECUTION_ID = p_batch_execution_id;

    DELETE FROM LOCF_AMORTIZATION_DTL
     WHERE BATCH_EXECUTION_ID = p_batch_execution_id;

    DELETE FROM LOCF_EIR_RESULT
     WHERE BATCH_EXECUTION_ID = p_batch_execution_id;

    DELETE FROM LOCF_CASHFLOW_BASE
     WHERE BATCH_EXECUTION_ID = p_batch_execution_id;

    DELETE FROM LOCF_TARGET_CONTRACT
     WHERE BATCH_EXECUTION_ID = p_batch_execution_id;
END;
/

CREATE OR REPLACE PROCEDURE PRC_LOCF_INSERT_TARGET_CONTRACTS (
    p_batch_execution_id IN NUMBER,
    p_base_date          IN DATE
) IS
BEGIN
    INSERT INTO LOCF_TARGET_CONTRACT (
        TARGET_ID, BATCH_EXECUTION_ID, CONTRACT_ID, CONTRACT_NO, CUSTOMER_ID, PRODUCT_CODE,
        REPAYMENT_TYPE, PRINCIPAL_AMT, FEE_AMT, DIRECT_COST_AMT, ANNUAL_NOMINAL_RATE,
        EXECUTION_DATE, MATURITY_DATE, TERM_IN_MONTHS
    )
    SELECT SQ_LOCF_TARGET_CONTRACT.NEXTVAL,
           p_batch_execution_id,
           c.CONTRACT_ID,
           c.CONTRACT_NO,
           c.CUSTOMER_ID,
           c.PRODUCT_CODE,
           c.REPAYMENT_TYPE,
           c.PRINCIPAL_AMT,
           c.FEE_AMT,
           c.DIRECT_COST_AMT,
           r.ANNUAL_NOMINAL_RATE,
           c.EXECUTION_DATE,
           c.MATURITY_DATE,
           (
               (EXTRACT(YEAR FROM c.MATURITY_DATE) - EXTRACT(YEAR FROM c.EXECUTION_DATE)) * 12
               + (EXTRACT(MONTH FROM c.MATURITY_DATE) - EXTRACT(MONTH FROM c.EXECUTION_DATE))
           )
        FROM LOAN_CONTRACT c,
             LOAN_RATE r,
             LOAN_BALANCE b
       WHERE r.CONTRACT_ID = c.CONTRACT_ID
         AND b.CONTRACT_ID = c.CONTRACT_ID
         AND c.STATUS_CODE = 'ACTIVE'
         AND b.BASE_DATE = p_base_date;
END;
/

CREATE OR REPLACE PROCEDURE PRC_LOCF_INSERT_RESULT_SUMMARY (
    p_batch_execution_id IN NUMBER
) IS
BEGIN
    INSERT INTO LOCF_RESULT_SUMMARY (
        SUMMARY_ID, BATCH_EXECUTION_ID, BASE_DATE, PRODUCT_CODE, CONTRACT_COUNT,
        TOTAL_INITIAL_CARRYING_AMT, TOTAL_FINAL_CARRYING_AMT, TOTAL_EFFECTIVE_INTEREST_REV, CREATED_AT
    )
    SELECT SQ_LOCF_RESULT_SUMMARY.NEXTVAL,
           summary_rows.BATCH_EXECUTION_ID,
           summary_rows.BASE_DATE,
           summary_rows.PRODUCT_CODE,
           summary_rows.CONTRACT_COUNT,
           summary_rows.TOTAL_INITIAL_CARRYING_AMT,
           summary_rows.TOTAL_FINAL_CARRYING_AMT,
           summary_rows.TOTAL_EFFECTIVE_INTEREST_REV,
           CURRENT_TIMESTAMP
      FROM (
            SELECT h.BATCH_EXECUTION_ID,
                   h.BASE_DATE,
                   h.PRODUCT_CODE,
                   COUNT(*) AS CONTRACT_COUNT,
                   SUM(h.INITIAL_CARRYING_AMOUNT) AS TOTAL_INITIAL_CARRYING_AMT,
                   SUM(h.FINAL_CARRYING_AMOUNT) AS TOTAL_FINAL_CARRYING_AMT,
                   SUM(h.TOTAL_EFFECTIVE_INTEREST_REV) AS TOTAL_EFFECTIVE_INTEREST_REV
              FROM LOCF_RESULT_HDR h
             WHERE h.BATCH_EXECUTION_ID = p_batch_execution_id
             GROUP BY h.BATCH_EXECUTION_ID, h.BASE_DATE, h.PRODUCT_CODE
      ) summary_rows;
END;
/

CREATE INDEX IX_LOCF_BATCH_EXEC_01 ON LOCF_BATCH_EXECUTION (BASE_DATE, STATUS_CODE);
CREATE INDEX IX_LOCF_TARGET_01 ON LOCF_TARGET_CONTRACT (BATCH_EXECUTION_ID, CONTRACT_ID);
CREATE INDEX IX_LOCF_CF_BASE_01 ON LOCF_CASHFLOW_BASE (BATCH_EXECUTION_ID, CONTRACT_ID, INSTALLMENT_NO);
CREATE INDEX IX_LOCF_EIR_01 ON LOCF_EIR_RESULT (BATCH_EXECUTION_ID, CONTRACT_ID);
CREATE INDEX IX_LOCF_AMORT_01 ON LOCF_AMORTIZATION_DTL (BATCH_EXECUTION_ID, CONTRACT_ID, INSTALLMENT_NO);
CREATE INDEX IX_LOCF_RESULT_HDR_01 ON LOCF_RESULT_HDR (BASE_DATE, CONTRACT_NO);
CREATE INDEX IX_LOCF_RESULT_SUM_01 ON LOCF_RESULT_SUMMARY (BASE_DATE, PRODUCT_CODE);
CREATE INDEX IX_CUSTOMER_MASTER_01 ON CUSTOMER_MASTER (CUSTOMER_NO);
CREATE INDEX IX_LOAN_CONTRACT_01 ON LOAN_CONTRACT (CONTRACT_NO, STATUS_CODE);
CREATE INDEX IX_LOAN_CONTRACT_02 ON LOAN_CONTRACT (CUSTOMER_ID, PRODUCT_CODE);
CREATE INDEX IX_LOAN_RATE_01 ON LOAN_RATE (CONTRACT_ID, EFFECTIVE_FROM);
CREATE INDEX IX_LOAN_REPAYMENT_SCHEDULE_01 ON LOAN_REPAYMENT_SCHEDULE (CONTRACT_ID, INSTALLMENT_NO);
CREATE INDEX IX_LOAN_BALANCE_01 ON LOAN_BALANCE (CONTRACT_ID, BASE_DATE);

COMMENT ON TABLE CUSTOMER_MASTER IS '고객 마스터';
COMMENT ON COLUMN CUSTOMER_MASTER.CUSTOMER_ID IS '고객ID';
COMMENT ON COLUMN CUSTOMER_MASTER.CUSTOMER_NO IS '고객번호';
COMMENT ON COLUMN CUSTOMER_MASTER.CUSTOMER_NAME IS '고객명';
COMMENT ON COLUMN CUSTOMER_MASTER.CUSTOMER_TYPE IS '고객유형';
COMMENT ON COLUMN CUSTOMER_MASTER.SEGMENT_CODE IS '세그먼트코드';
COMMENT ON COLUMN CUSTOMER_MASTER.STATUS_CODE IS '상태코드';
COMMENT ON COLUMN CUSTOMER_MASTER.CREATED_AT IS '생성일시';
COMMENT ON COLUMN CUSTOMER_MASTER.UPDATED_AT IS '수정일시';

COMMENT ON TABLE LOAN_CONTRACT IS '여신 계약 원장';
COMMENT ON COLUMN LOAN_CONTRACT.CONTRACT_ID IS '계약ID';
COMMENT ON COLUMN LOAN_CONTRACT.CONTRACT_NO IS '계약번호';
COMMENT ON COLUMN LOAN_CONTRACT.CUSTOMER_ID IS '고객ID';
COMMENT ON COLUMN LOAN_CONTRACT.PRODUCT_CODE IS '상품코드';
COMMENT ON COLUMN LOAN_CONTRACT.LOAN_TYPE_CODE IS '여신유형코드';
COMMENT ON COLUMN LOAN_CONTRACT.REPAYMENT_TYPE IS '상환방식';
COMMENT ON COLUMN LOAN_CONTRACT.EXECUTION_DATE IS '실행일자';
COMMENT ON COLUMN LOAN_CONTRACT.MATURITY_DATE IS '만기일자';
COMMENT ON COLUMN LOAN_CONTRACT.PRINCIPAL_AMT IS '원금금액';
COMMENT ON COLUMN LOAN_CONTRACT.FEE_AMT IS '취급수수료금액';
COMMENT ON COLUMN LOAN_CONTRACT.DIRECT_COST_AMT IS '직접원가금액';
COMMENT ON COLUMN LOAN_CONTRACT.STATUS_CODE IS '상태코드';
COMMENT ON COLUMN LOAN_CONTRACT.CREATED_AT IS '생성일시';
COMMENT ON COLUMN LOAN_CONTRACT.UPDATED_AT IS '수정일시';

COMMENT ON TABLE LOAN_RATE IS '여신 금리 이력';
COMMENT ON COLUMN LOAN_RATE.RATE_ID IS '금리ID';
COMMENT ON COLUMN LOAN_RATE.CONTRACT_ID IS '계약ID';
COMMENT ON COLUMN LOAN_RATE.RATE_TYPE IS '금리유형';
COMMENT ON COLUMN LOAN_RATE.ANNUAL_NOMINAL_RATE IS '연약정금리';
COMMENT ON COLUMN LOAN_RATE.EFFECTIVE_FROM IS '적용시작일자';
COMMENT ON COLUMN LOAN_RATE.EFFECTIVE_TO IS '적용종료일자';
COMMENT ON COLUMN LOAN_RATE.CREATED_AT IS '생성일시';
COMMENT ON COLUMN LOAN_RATE.UPDATED_AT IS '수정일시';

COMMENT ON TABLE LOAN_REPAYMENT_SCHEDULE IS '여신 상환 스케줄';
COMMENT ON COLUMN LOAN_REPAYMENT_SCHEDULE.SCHEDULE_ID IS '상환스케줄ID';
COMMENT ON COLUMN LOAN_REPAYMENT_SCHEDULE.CONTRACT_ID IS '계약ID';
COMMENT ON COLUMN LOAN_REPAYMENT_SCHEDULE.INSTALLMENT_NO IS '회차';
COMMENT ON COLUMN LOAN_REPAYMENT_SCHEDULE.PAYMENT_DATE IS '상환일자';
COMMENT ON COLUMN LOAN_REPAYMENT_SCHEDULE.SCHEDULED_PAYMENT_AMT IS '약정납입금액';
COMMENT ON COLUMN LOAN_REPAYMENT_SCHEDULE.SCHEDULED_PRINCIPAL_AMT IS '약정원금금액';
COMMENT ON COLUMN LOAN_REPAYMENT_SCHEDULE.SCHEDULED_INTEREST_AMT IS '약정이자금액';
COMMENT ON COLUMN LOAN_REPAYMENT_SCHEDULE.CREATED_AT IS '생성일시';
COMMENT ON COLUMN LOAN_REPAYMENT_SCHEDULE.UPDATED_AT IS '수정일시';

COMMENT ON TABLE LOAN_BALANCE IS '여신 잔액 원장';
COMMENT ON COLUMN LOAN_BALANCE.BALANCE_ID IS '잔액ID';
COMMENT ON COLUMN LOAN_BALANCE.CONTRACT_ID IS '계약ID';
COMMENT ON COLUMN LOAN_BALANCE.BASE_DATE IS '기준일자';
COMMENT ON COLUMN LOAN_BALANCE.OUTSTANDING_PRINCIPAL_AMT IS '원금잔액금액';
COMMENT ON COLUMN LOAN_BALANCE.ACCRUED_INTEREST_AMT IS '미수이자금액';
COMMENT ON COLUMN LOAN_BALANCE.STATUS_CODE IS '상태코드';
COMMENT ON COLUMN LOAN_BALANCE.CREATED_AT IS '생성일시';
COMMENT ON COLUMN LOAN_BALANCE.UPDATED_AT IS '수정일시';

COMMENT ON TABLE LOCF_BATCH_EXECUTION IS 'LOCF 배치 실행 이력';
COMMENT ON COLUMN LOCF_BATCH_EXECUTION.BATCH_EXECUTION_ID IS '배치실행ID';
COMMENT ON COLUMN LOCF_BATCH_EXECUTION.BATCH_RUN_NO IS '배치실행번호';
COMMENT ON COLUMN LOCF_BATCH_EXECUTION.BASE_DATE IS '기준일자';
COMMENT ON COLUMN LOCF_BATCH_EXECUTION.BATCH_TYPE IS '배치유형';
COMMENT ON COLUMN LOCF_BATCH_EXECUTION.STATUS_CODE IS '상태코드';
COMMENT ON COLUMN LOCF_BATCH_EXECUTION.TARGET_COUNT IS '대상건수';
COMMENT ON COLUMN LOCF_BATCH_EXECUTION.PROCESSED_COUNT IS '처리건수';
COMMENT ON COLUMN LOCF_BATCH_EXECUTION.ERROR_COUNT IS '오류건수';
COMMENT ON COLUMN LOCF_BATCH_EXECUTION.STARTED_AT IS '시작일시';
COMMENT ON COLUMN LOCF_BATCH_EXECUTION.FINISHED_AT IS '종료일시';
COMMENT ON COLUMN LOCF_BATCH_EXECUTION.ERROR_MESSAGE IS '오류메시지';

COMMENT ON TABLE LOCF_BATCH_STEP_EXECUTION IS 'LOCF 배치 단계 실행 이력';
COMMENT ON COLUMN LOCF_BATCH_STEP_EXECUTION.STEP_EXECUTION_ID IS '단계실행ID';
COMMENT ON COLUMN LOCF_BATCH_STEP_EXECUTION.BATCH_EXECUTION_ID IS '배치실행ID';
COMMENT ON COLUMN LOCF_BATCH_STEP_EXECUTION.STEP_NAME IS '단계명';
COMMENT ON COLUMN LOCF_BATCH_STEP_EXECUTION.STATUS_CODE IS '상태코드';
COMMENT ON COLUMN LOCF_BATCH_STEP_EXECUTION.STARTED_AT IS '시작일시';
COMMENT ON COLUMN LOCF_BATCH_STEP_EXECUTION.FINISHED_AT IS '종료일시';
COMMENT ON COLUMN LOCF_BATCH_STEP_EXECUTION.PROCESSED_COUNT IS '처리건수';
COMMENT ON COLUMN LOCF_BATCH_STEP_EXECUTION.ERROR_MESSAGE IS '오류메시지';

COMMENT ON TABLE LOCF_TARGET_CONTRACT IS 'LOCF 산출 대상 계약';
COMMENT ON COLUMN LOCF_TARGET_CONTRACT.TARGET_ID IS '대상ID';
COMMENT ON COLUMN LOCF_TARGET_CONTRACT.BATCH_EXECUTION_ID IS '배치실행ID';
COMMENT ON COLUMN LOCF_TARGET_CONTRACT.CONTRACT_ID IS '계약ID';
COMMENT ON COLUMN LOCF_TARGET_CONTRACT.CONTRACT_NO IS '계약번호';
COMMENT ON COLUMN LOCF_TARGET_CONTRACT.CUSTOMER_ID IS '고객ID';
COMMENT ON COLUMN LOCF_TARGET_CONTRACT.PRODUCT_CODE IS '상품코드';
COMMENT ON COLUMN LOCF_TARGET_CONTRACT.REPAYMENT_TYPE IS '상환방식';
COMMENT ON COLUMN LOCF_TARGET_CONTRACT.PRINCIPAL_AMT IS '원금금액';
COMMENT ON COLUMN LOCF_TARGET_CONTRACT.FEE_AMT IS '취급수수료금액';
COMMENT ON COLUMN LOCF_TARGET_CONTRACT.DIRECT_COST_AMT IS '직접원가금액';
COMMENT ON COLUMN LOCF_TARGET_CONTRACT.ANNUAL_NOMINAL_RATE IS '연약정금리';
COMMENT ON COLUMN LOCF_TARGET_CONTRACT.EXECUTION_DATE IS '실행일자';
COMMENT ON COLUMN LOCF_TARGET_CONTRACT.MATURITY_DATE IS '만기일자';
COMMENT ON COLUMN LOCF_TARGET_CONTRACT.TERM_IN_MONTHS IS '총개월수';

COMMENT ON TABLE LOCF_CASHFLOW_BASE IS 'LOCF 약정 현금흐름 기초';
COMMENT ON COLUMN LOCF_CASHFLOW_BASE.CASHFLOW_BASE_ID IS '현금흐름기초ID';
COMMENT ON COLUMN LOCF_CASHFLOW_BASE.BATCH_EXECUTION_ID IS '배치실행ID';
COMMENT ON COLUMN LOCF_CASHFLOW_BASE.CONTRACT_ID IS '계약ID';
COMMENT ON COLUMN LOCF_CASHFLOW_BASE.CONTRACT_NO IS '계약번호';
COMMENT ON COLUMN LOCF_CASHFLOW_BASE.INSTALLMENT_NO IS '회차';
COMMENT ON COLUMN LOCF_CASHFLOW_BASE.PAYMENT_DATE IS '상환일자';
COMMENT ON COLUMN LOCF_CASHFLOW_BASE.SCHEDULED_PAYMENT_AMT IS '약정납입금액';
COMMENT ON COLUMN LOCF_CASHFLOW_BASE.SCHEDULED_PRINCIPAL_AMT IS '약정원금금액';
COMMENT ON COLUMN LOCF_CASHFLOW_BASE.SCHEDULED_INTEREST_AMT IS '약정이자금액';

COMMENT ON TABLE LOCF_EIR_RESULT IS 'LOCF 유효이자율 산출 결과';
COMMENT ON COLUMN LOCF_EIR_RESULT.EIR_RESULT_ID IS 'EIR결과ID';
COMMENT ON COLUMN LOCF_EIR_RESULT.BATCH_EXECUTION_ID IS '배치실행ID';
COMMENT ON COLUMN LOCF_EIR_RESULT.CONTRACT_ID IS '계약ID';
COMMENT ON COLUMN LOCF_EIR_RESULT.CONTRACT_NO IS '계약번호';
COMMENT ON COLUMN LOCF_EIR_RESULT.INITIAL_CARRYING_AMOUNT IS '최초장부가금액';
COMMENT ON COLUMN LOCF_EIR_RESULT.MONTHLY_EIR IS '월유효이자율';
COMMENT ON COLUMN LOCF_EIR_RESULT.ANNUAL_EIR IS '연유효이자율';

COMMENT ON TABLE LOCF_AMORTIZATION_DTL IS 'LOCF 회차별 상각 상세';
COMMENT ON COLUMN LOCF_AMORTIZATION_DTL.AMORTIZATION_DTL_ID IS '상각상세ID';
COMMENT ON COLUMN LOCF_AMORTIZATION_DTL.BATCH_EXECUTION_ID IS '배치실행ID';
COMMENT ON COLUMN LOCF_AMORTIZATION_DTL.CONTRACT_ID IS '계약ID';
COMMENT ON COLUMN LOCF_AMORTIZATION_DTL.CONTRACT_NO IS '계약번호';
COMMENT ON COLUMN LOCF_AMORTIZATION_DTL.INSTALLMENT_NO IS '회차';
COMMENT ON COLUMN LOCF_AMORTIZATION_DTL.PAYMENT_DATE IS '상환일자';
COMMENT ON COLUMN LOCF_AMORTIZATION_DTL.OPENING_PRINCIPAL_BAL IS '기초원금잔액';
COMMENT ON COLUMN LOCF_AMORTIZATION_DTL.OPENING_CARRYING_AMT IS '기초장부가금액';
COMMENT ON COLUMN LOCF_AMORTIZATION_DTL.SCHEDULED_PAYMENT_AMT IS '약정납입금액';
COMMENT ON COLUMN LOCF_AMORTIZATION_DTL.SCHEDULED_PRINCIPAL_AMT IS '약정원금금액';
COMMENT ON COLUMN LOCF_AMORTIZATION_DTL.SCHEDULED_INTEREST_AMT IS '약정이자금액';
COMMENT ON COLUMN LOCF_AMORTIZATION_DTL.EFFECTIVE_INTEREST_REVENUE IS '유효이자수익금액';
COMMENT ON COLUMN LOCF_AMORTIZATION_DTL.FEE_AMORTIZATION_AMT IS '수수료상각금액';
COMMENT ON COLUMN LOCF_AMORTIZATION_DTL.COST_AMORTIZATION_AMT IS '직접원가상각금액';
COMMENT ON COLUMN LOCF_AMORTIZATION_DTL.NET_AMORTIZATION_AMT IS '순상각금액';
COMMENT ON COLUMN LOCF_AMORTIZATION_DTL.CLOSING_PRINCIPAL_BAL IS '기말원금잔액';
COMMENT ON COLUMN LOCF_AMORTIZATION_DTL.CLOSING_CARRYING_AMT IS '기말장부가금액';

COMMENT ON TABLE LOCF_RESULT_HDR IS 'LOCF 계약별 결과 헤더';
COMMENT ON COLUMN LOCF_RESULT_HDR.RESULT_HDR_ID IS '결과헤더ID';
COMMENT ON COLUMN LOCF_RESULT_HDR.BATCH_EXECUTION_ID IS '배치실행ID';
COMMENT ON COLUMN LOCF_RESULT_HDR.BASE_DATE IS '기준일자';
COMMENT ON COLUMN LOCF_RESULT_HDR.CONTRACT_ID IS '계약ID';
COMMENT ON COLUMN LOCF_RESULT_HDR.CONTRACT_NO IS '계약번호';
COMMENT ON COLUMN LOCF_RESULT_HDR.CUSTOMER_ID IS '고객ID';
COMMENT ON COLUMN LOCF_RESULT_HDR.PRODUCT_CODE IS '상품코드';
COMMENT ON COLUMN LOCF_RESULT_HDR.PRINCIPAL_AMT IS '원금금액';
COMMENT ON COLUMN LOCF_RESULT_HDR.INITIAL_CARRYING_AMOUNT IS '최초장부가금액';
COMMENT ON COLUMN LOCF_RESULT_HDR.ANNUAL_EIR IS '연유효이자율';
COMMENT ON COLUMN LOCF_RESULT_HDR.FINAL_CARRYING_AMOUNT IS '최종장부가금액';
COMMENT ON COLUMN LOCF_RESULT_HDR.TOTAL_EFFECTIVE_INTEREST_REV IS '총유효이자수익금액';
COMMENT ON COLUMN LOCF_RESULT_HDR.TOTAL_FEE_AMORTIZATION_AMT IS '총수수료상각금액';
COMMENT ON COLUMN LOCF_RESULT_HDR.TOTAL_COST_AMORTIZATION_AMT IS '총직접원가상각금액';
COMMENT ON COLUMN LOCF_RESULT_HDR.CREATED_AT IS '생성일시';

COMMENT ON TABLE LOCF_RESULT_SUMMARY IS 'LOCF 기준일자 요약 결과';
COMMENT ON COLUMN LOCF_RESULT_SUMMARY.SUMMARY_ID IS '요약ID';
COMMENT ON COLUMN LOCF_RESULT_SUMMARY.BATCH_EXECUTION_ID IS '배치실행ID';
COMMENT ON COLUMN LOCF_RESULT_SUMMARY.BASE_DATE IS '기준일자';
COMMENT ON COLUMN LOCF_RESULT_SUMMARY.PRODUCT_CODE IS '상품코드';
COMMENT ON COLUMN LOCF_RESULT_SUMMARY.CONTRACT_COUNT IS '계약건수';
COMMENT ON COLUMN LOCF_RESULT_SUMMARY.TOTAL_INITIAL_CARRYING_AMT IS '최초장부가합계금액';
COMMENT ON COLUMN LOCF_RESULT_SUMMARY.TOTAL_FINAL_CARRYING_AMT IS '최종장부가합계금액';
COMMENT ON COLUMN LOCF_RESULT_SUMMARY.TOTAL_EFFECTIVE_INTEREST_REV IS '총유효이자수익금액';
COMMENT ON COLUMN LOCF_RESULT_SUMMARY.CREATED_AT IS '생성일시';
