-- LOCF_USER 로 접속한 상태에서 실행한다.
-- 전제:
-- 1. 03_create_locf_tables.sql 이 먼저 실행되어 공통 원천/LOCF 테이블이 생성되어 있어야 한다.
-- 2. 이 스크립트는 충당금 산출용 보강 원천 테이블과 PRV_* 배치 테이블/프로시저를 생성한다.

BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRV_ECL_RESULT_SUMMARY CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRV_ECL_RESULT_DTL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRV_LGD_RESULT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRV_PD_RESULT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRV_EAD_RESULT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRV_STAGE_RESULT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRV_TARGET_CONTRACT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRV_BATCH_STEP_EXECUTION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRV_BATCH_EXECUTION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOAN_COLLATERAL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOAN_DELINQUENCY CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER_RATING CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_PRV_ECL_RESULT_SUMMARY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_PRV_ECL_RESULT_DTL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_PRV_LGD_RESULT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_PRV_PD_RESULT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_PRV_EAD_RESULT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_PRV_STAGE_RESULT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_PRV_TARGET_CONTRACT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_PRV_BATCH_STEP_EXECUTION'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_PRV_BATCH_EXECUTION'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_LOAN_COLLATERAL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_LOAN_DELINQUENCY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CUSTOMER_RATING'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_PRV_INSERT_RESULT_SUMMARY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_PRV_CALCULATE_ECL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_PRV_CALCULATE_LGD'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_PRV_CALCULATE_PD'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_PRV_CALCULATE_EAD'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_PRV_CALCULATE_STAGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_PRV_INSERT_TARGET_CONTRACTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_PRV_CLEAR_BATCH_DATA'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/

CREATE TABLE CUSTOMER_RATING (
    RATING_ID NUMBER(19,0) PRIMARY KEY,
    CUSTOMER_ID NUMBER(19,0) NOT NULL,
    BASE_DATE DATE NOT NULL,
    RATING_GRADE VARCHAR2(20 CHAR) NOT NULL,
    ONE_YEAR_PD_RATE NUMBER(18,10) NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT FK_CUSTOMER_RATING_01 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_MASTER (CUSTOMER_ID)
);

CREATE TABLE LOAN_DELINQUENCY (
    DELINQUENCY_ID NUMBER(19,0) PRIMARY KEY,
    CONTRACT_ID NUMBER(19,0) NOT NULL,
    BASE_DATE DATE NOT NULL,
    DELINQUENCY_DAYS NUMBER(8,0) NOT NULL,
    DEFAULT_YN VARCHAR2(1 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT FK_LOAN_DELINQUENCY_01 FOREIGN KEY (CONTRACT_ID) REFERENCES LOAN_CONTRACT (CONTRACT_ID)
);

CREATE TABLE LOAN_COLLATERAL (
    COLLATERAL_ID NUMBER(19,0) PRIMARY KEY,
    CONTRACT_ID NUMBER(19,0) NOT NULL,
    BASE_DATE DATE NOT NULL,
    COLLATERAL_TYPE VARCHAR2(30 CHAR) NOT NULL,
    COLLATERAL_VALUE_AMT NUMBER(18,2) NOT NULL,
    RECOVERY_RATE NUMBER(18,10) NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT FK_LOAN_COLLATERAL_01 FOREIGN KEY (CONTRACT_ID) REFERENCES LOAN_CONTRACT (CONTRACT_ID)
);

CREATE TABLE PRV_BATCH_EXECUTION (
    BATCH_EXECUTION_ID NUMBER(19,0) PRIMARY KEY,
    BATCH_RUN_NO VARCHAR2(40 CHAR) NOT NULL UNIQUE,
    BASE_DATE DATE NOT NULL,
    BATCH_TYPE VARCHAR2(20 CHAR) NOT NULL,
    STATUS_CODE VARCHAR2(20 CHAR) NOT NULL,
    TARGET_COUNT NUMBER(12,0) NOT NULL,
    PROCESSED_COUNT NUMBER(12,0) NOT NULL,
    ERROR_COUNT NUMBER(12,0) NOT NULL,
    STARTED_AT TIMESTAMP(6) NOT NULL,
    FINISHED_AT TIMESTAMP(6),
    ERROR_MESSAGE VARCHAR2(1000 CHAR)
);

CREATE TABLE PRV_BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID NUMBER(19,0) PRIMARY KEY,
    BATCH_EXECUTION_ID NUMBER(19,0) NOT NULL,
    STEP_NAME VARCHAR2(50 CHAR) NOT NULL,
    STATUS_CODE VARCHAR2(20 CHAR) NOT NULL,
    STARTED_AT TIMESTAMP(6) NOT NULL,
    FINISHED_AT TIMESTAMP(6),
    PROCESSED_COUNT NUMBER(12,0) NOT NULL,
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    CONSTRAINT FK_PRV_STEP_EXEC_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES PRV_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE PRV_TARGET_CONTRACT (
    TARGET_ID NUMBER(19,0) PRIMARY KEY,
    BATCH_EXECUTION_ID NUMBER(19,0) NOT NULL,
    BASE_DATE DATE NOT NULL,
    CONTRACT_ID NUMBER(19,0) NOT NULL,
    CONTRACT_NO VARCHAR2(30 CHAR) NOT NULL,
    CUSTOMER_ID NUMBER(19,0) NOT NULL,
    CUSTOMER_NAME VARCHAR2(100 CHAR) NOT NULL,
    PRODUCT_CODE VARCHAR2(30 CHAR) NOT NULL,
    OUTSTANDING_PRINCIPAL_AMT NUMBER(18,2) NOT NULL,
    CARRYING_AMOUNT NUMBER(18,2) NOT NULL,
    DELINQUENCY_DAYS NUMBER(8,0) NOT NULL,
    DEFAULT_YN VARCHAR2(1 CHAR) NOT NULL,
    RATING_GRADE VARCHAR2(20 CHAR) NOT NULL,
    ONE_YEAR_PD_RATE NUMBER(18,10) NOT NULL,
    COLLATERAL_VALUE_AMT NUMBER(18,2) NOT NULL,
    RECOVERY_RATE NUMBER(18,10) NOT NULL,
    CONSTRAINT FK_PRV_TARGET_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES PRV_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE PRV_STAGE_RESULT (
    STAGE_RESULT_ID NUMBER(19,0) PRIMARY KEY,
    BATCH_EXECUTION_ID NUMBER(19,0) NOT NULL,
    TARGET_ID NUMBER(19,0) NOT NULL,
    CONTRACT_ID NUMBER(19,0) NOT NULL,
    CONTRACT_NO VARCHAR2(30 CHAR) NOT NULL,
    STAGE_CODE VARCHAR2(20 CHAR) NOT NULL,
    STAGE_REASON VARCHAR2(100 CHAR) NOT NULL,
    CONSTRAINT FK_PRV_STAGE_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES PRV_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE PRV_EAD_RESULT (
    EAD_RESULT_ID NUMBER(19,0) PRIMARY KEY,
    BATCH_EXECUTION_ID NUMBER(19,0) NOT NULL,
    TARGET_ID NUMBER(19,0) NOT NULL,
    CONTRACT_ID NUMBER(19,0) NOT NULL,
    CONTRACT_NO VARCHAR2(30 CHAR) NOT NULL,
    CARRYING_AMOUNT NUMBER(18,2) NOT NULL,
    EAD_AMOUNT NUMBER(18,2) NOT NULL,
    CONSTRAINT FK_PRV_EAD_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES PRV_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE PRV_PD_RESULT (
    PD_RESULT_ID NUMBER(19,0) PRIMARY KEY,
    BATCH_EXECUTION_ID NUMBER(19,0) NOT NULL,
    TARGET_ID NUMBER(19,0) NOT NULL,
    CONTRACT_ID NUMBER(19,0) NOT NULL,
    CONTRACT_NO VARCHAR2(30 CHAR) NOT NULL,
    STAGE_CODE VARCHAR2(20 CHAR) NOT NULL,
    ONE_YEAR_PD_RATE NUMBER(18,10) NOT NULL,
    LIFETIME_PD_RATE NUMBER(18,10) NOT NULL,
    CONSTRAINT FK_PRV_PD_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES PRV_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE PRV_LGD_RESULT (
    LGD_RESULT_ID NUMBER(19,0) PRIMARY KEY,
    BATCH_EXECUTION_ID NUMBER(19,0) NOT NULL,
    TARGET_ID NUMBER(19,0) NOT NULL,
    CONTRACT_ID NUMBER(19,0) NOT NULL,
    CONTRACT_NO VARCHAR2(30 CHAR) NOT NULL,
    RECOVERY_RATE NUMBER(18,10) NOT NULL,
    LGD_RATE NUMBER(18,10) NOT NULL,
    CONSTRAINT FK_PRV_LGD_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES PRV_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE PRV_ECL_RESULT_DTL (
    RESULT_DTL_ID NUMBER(19,0) PRIMARY KEY,
    BATCH_EXECUTION_ID NUMBER(19,0) NOT NULL,
    BASE_DATE DATE NOT NULL,
    CONTRACT_ID NUMBER(19,0) NOT NULL,
    CONTRACT_NO VARCHAR2(30 CHAR) NOT NULL,
    CUSTOMER_NAME VARCHAR2(100 CHAR) NOT NULL,
    PRODUCT_CODE VARCHAR2(30 CHAR) NOT NULL,
    STAGE_CODE VARCHAR2(20 CHAR) NOT NULL,
    STAGE_REASON VARCHAR2(100 CHAR) NOT NULL,
    CARRYING_AMOUNT NUMBER(18,2) NOT NULL,
    EAD_AMOUNT NUMBER(18,2) NOT NULL,
    ONE_YEAR_PD_RATE NUMBER(18,10) NOT NULL,
    LIFETIME_PD_RATE NUMBER(18,10) NOT NULL,
    LGD_RATE NUMBER(18,10) NOT NULL,
    RECOVERY_RATE NUMBER(18,10) NOT NULL,
    ECL_AMOUNT NUMBER(18,2) NOT NULL,
    CONSTRAINT FK_PRV_ECL_DTL_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES PRV_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE PRV_ECL_RESULT_SUMMARY (
    SUMMARY_ID NUMBER(19,0) PRIMARY KEY,
    BATCH_EXECUTION_ID NUMBER(19,0) NOT NULL,
    BASE_DATE DATE NOT NULL,
    PRODUCT_CODE VARCHAR2(30 CHAR) NOT NULL,
    STAGE_CODE VARCHAR2(20 CHAR) NOT NULL,
    CONTRACT_COUNT NUMBER(12,0) NOT NULL,
    TOTAL_CARRYING_AMOUNT NUMBER(18,2) NOT NULL,
    TOTAL_EAD_AMOUNT NUMBER(18,2) NOT NULL,
    TOTAL_ECL_AMOUNT NUMBER(18,2) NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT FK_PRV_ECL_SUM_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES PRV_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE SEQUENCE SQ_CUSTOMER_RATING START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_LOAN_DELINQUENCY START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_LOAN_COLLATERAL START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_PRV_BATCH_EXECUTION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_PRV_BATCH_STEP_EXECUTION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_PRV_TARGET_CONTRACT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_PRV_STAGE_RESULT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_PRV_EAD_RESULT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_PRV_PD_RESULT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_PRV_LGD_RESULT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_PRV_ECL_RESULT_DTL START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_PRV_ECL_RESULT_SUMMARY START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE PROCEDURE PRC_PRV_CLEAR_BATCH_DATA (p_batch_execution_id IN NUMBER) IS
BEGIN
    DELETE FROM PRV_ECL_RESULT_SUMMARY WHERE BATCH_EXECUTION_ID = p_batch_execution_id;
    DELETE FROM PRV_ECL_RESULT_DTL WHERE BATCH_EXECUTION_ID = p_batch_execution_id;
    DELETE FROM PRV_LGD_RESULT WHERE BATCH_EXECUTION_ID = p_batch_execution_id;
    DELETE FROM PRV_PD_RESULT WHERE BATCH_EXECUTION_ID = p_batch_execution_id;
    DELETE FROM PRV_EAD_RESULT WHERE BATCH_EXECUTION_ID = p_batch_execution_id;
    DELETE FROM PRV_STAGE_RESULT WHERE BATCH_EXECUTION_ID = p_batch_execution_id;
    DELETE FROM PRV_TARGET_CONTRACT WHERE BATCH_EXECUTION_ID = p_batch_execution_id;
END;
/

CREATE OR REPLACE PROCEDURE PRC_PRV_INSERT_TARGET_CONTRACTS (
    p_batch_execution_id IN NUMBER,
    p_base_date          IN DATE
) IS
BEGIN
    INSERT INTO PRV_TARGET_CONTRACT (
        TARGET_ID, BATCH_EXECUTION_ID, BASE_DATE, CONTRACT_ID, CONTRACT_NO, CUSTOMER_ID, CUSTOMER_NAME, PRODUCT_CODE,
        OUTSTANDING_PRINCIPAL_AMT, CARRYING_AMOUNT, DELINQUENCY_DAYS, DEFAULT_YN, RATING_GRADE, ONE_YEAR_PD_RATE,
        COLLATERAL_VALUE_AMT, RECOVERY_RATE
    )
    SELECT SQ_PRV_TARGET_CONTRACT.NEXTVAL,
           p_batch_execution_id,
           p_base_date,
           c.CONTRACT_ID,
           c.CONTRACT_NO,
           c.CUSTOMER_ID,
           cm.CUSTOMER_NAME,
           c.PRODUCT_CODE,
           b.OUTSTANDING_PRINCIPAL_AMT,
           NVL((
               SELECT d.CLOSING_CARRYING_AMT
                 FROM LOCF_AMORTIZATION_DTL d
                WHERE d.CONTRACT_ID = c.CONTRACT_ID
                  AND d.PAYMENT_DATE <= p_base_date
                ORDER BY d.PAYMENT_DATE DESC, d.INSTALLMENT_NO DESC
                FETCH FIRST 1 ROWS ONLY
           ), NVL((
               SELECT e.INITIAL_CARRYING_AMOUNT
                 FROM LOCF_EIR_RESULT e
                WHERE e.CONTRACT_ID = c.CONTRACT_ID
                ORDER BY e.EIR_RESULT_ID DESC
                FETCH FIRST 1 ROWS ONLY
           ), b.OUTSTANDING_PRINCIPAL_AMT)),
           NVL(d.DELINQUENCY_DAYS, 0),
           NVL(d.DEFAULT_YN, 'N'),
           NVL(rg.RATING_GRADE, 'B'),
           NVL(rg.ONE_YEAR_PD_RATE, 0.0300),
           NVL(cl.COLLATERAL_VALUE_AMT, 0),
           NVL(cl.RECOVERY_RATE, 0.20)
      FROM LOAN_CONTRACT c
      JOIN CUSTOMER_MASTER cm
        ON cm.CUSTOMER_ID = c.CUSTOMER_ID
      JOIN LOAN_BALANCE b
        ON b.CONTRACT_ID = c.CONTRACT_ID
       AND b.BASE_DATE = p_base_date
      LEFT JOIN LOAN_DELINQUENCY d
        ON d.CONTRACT_ID = c.CONTRACT_ID
       AND d.BASE_DATE = p_base_date
      LEFT JOIN CUSTOMER_RATING rg
        ON rg.CUSTOMER_ID = c.CUSTOMER_ID
       AND rg.BASE_DATE = p_base_date
      LEFT JOIN LOAN_COLLATERAL cl
        ON cl.CONTRACT_ID = c.CONTRACT_ID
       AND cl.BASE_DATE = p_base_date
     WHERE c.STATUS_CODE = 'ACTIVE';
END;
/

CREATE OR REPLACE PROCEDURE PRC_PRV_CALCULATE_STAGE (p_batch_execution_id IN NUMBER) IS
BEGIN
    INSERT INTO PRV_STAGE_RESULT (STAGE_RESULT_ID, BATCH_EXECUTION_ID, TARGET_ID, CONTRACT_ID, CONTRACT_NO, STAGE_CODE, STAGE_REASON)
    SELECT SQ_PRV_STAGE_RESULT.NEXTVAL,
           BATCH_EXECUTION_ID,
           TARGET_ID,
           CONTRACT_ID,
           CONTRACT_NO,
           CASE
               WHEN DEFAULT_YN = 'Y' OR DELINQUENCY_DAYS >= 90 THEN 'STAGE3'
               WHEN DELINQUENCY_DAYS >= 30 THEN 'STAGE2'
               ELSE 'STAGE1'
           END,
           CASE
               WHEN DEFAULT_YN = 'Y' THEN '부도차주'
               WHEN DELINQUENCY_DAYS >= 90 THEN '90일이상연체'
               WHEN DELINQUENCY_DAYS >= 30 THEN '30일이상연체'
               ELSE '정상계약'
           END
      FROM PRV_TARGET_CONTRACT
     WHERE BATCH_EXECUTION_ID = p_batch_execution_id;
END;
/

CREATE OR REPLACE PROCEDURE PRC_PRV_CALCULATE_EAD (p_batch_execution_id IN NUMBER) IS
BEGIN
    INSERT INTO PRV_EAD_RESULT (EAD_RESULT_ID, BATCH_EXECUTION_ID, TARGET_ID, CONTRACT_ID, CONTRACT_NO, CARRYING_AMOUNT, EAD_AMOUNT)
    SELECT SQ_PRV_EAD_RESULT.NEXTVAL,
           BATCH_EXECUTION_ID,
           TARGET_ID,
           CONTRACT_ID,
           CONTRACT_NO,
           CARRYING_AMOUNT,
           CARRYING_AMOUNT
      FROM PRV_TARGET_CONTRACT
     WHERE BATCH_EXECUTION_ID = p_batch_execution_id;
END;
/

CREATE OR REPLACE PROCEDURE PRC_PRV_CALCULATE_PD (p_batch_execution_id IN NUMBER) IS
BEGIN
    INSERT INTO PRV_PD_RESULT (PD_RESULT_ID, BATCH_EXECUTION_ID, TARGET_ID, CONTRACT_ID, CONTRACT_NO, STAGE_CODE, ONE_YEAR_PD_RATE, LIFETIME_PD_RATE)
    SELECT SQ_PRV_PD_RESULT.NEXTVAL,
           t.BATCH_EXECUTION_ID,
           t.TARGET_ID,
           t.CONTRACT_ID,
           t.CONTRACT_NO,
           s.STAGE_CODE,
           t.ONE_YEAR_PD_RATE,
           CASE
               WHEN s.STAGE_CODE = 'STAGE1' THEN t.ONE_YEAR_PD_RATE
               WHEN s.STAGE_CODE = 'STAGE2' THEN LEAST(t.ONE_YEAR_PD_RATE * 2.5, 1)
               ELSE LEAST(t.ONE_YEAR_PD_RATE * 4, 1)
           END
      FROM PRV_TARGET_CONTRACT t
      JOIN PRV_STAGE_RESULT s
        ON s.TARGET_ID = t.TARGET_ID
     WHERE t.BATCH_EXECUTION_ID = p_batch_execution_id;
END;
/

CREATE OR REPLACE PROCEDURE PRC_PRV_CALCULATE_LGD (p_batch_execution_id IN NUMBER) IS
BEGIN
    INSERT INTO PRV_LGD_RESULT (LGD_RESULT_ID, BATCH_EXECUTION_ID, TARGET_ID, CONTRACT_ID, CONTRACT_NO, RECOVERY_RATE, LGD_RATE)
    SELECT SQ_PRV_LGD_RESULT.NEXTVAL,
           BATCH_EXECUTION_ID,
           TARGET_ID,
           CONTRACT_ID,
           CONTRACT_NO,
           RECOVERY_RATE,
           CASE WHEN (1 - RECOVERY_RATE) < 0.15 THEN 0.15 ELSE (1 - RECOVERY_RATE) END
      FROM PRV_TARGET_CONTRACT
     WHERE BATCH_EXECUTION_ID = p_batch_execution_id;
END;
/

CREATE OR REPLACE PROCEDURE PRC_PRV_CALCULATE_ECL (p_batch_execution_id IN NUMBER) IS
BEGIN
    INSERT INTO PRV_ECL_RESULT_DTL (
        RESULT_DTL_ID, BATCH_EXECUTION_ID, BASE_DATE, CONTRACT_ID, CONTRACT_NO, CUSTOMER_NAME, PRODUCT_CODE,
        STAGE_CODE, STAGE_REASON, CARRYING_AMOUNT, EAD_AMOUNT, ONE_YEAR_PD_RATE, LIFETIME_PD_RATE,
        LGD_RATE, RECOVERY_RATE, ECL_AMOUNT
    )
    SELECT SQ_PRV_ECL_RESULT_DTL.NEXTVAL,
           t.BATCH_EXECUTION_ID,
           t.BASE_DATE,
           t.CONTRACT_ID,
           t.CONTRACT_NO,
           t.CUSTOMER_NAME,
           t.PRODUCT_CODE,
           s.STAGE_CODE,
           s.STAGE_REASON,
           e.CARRYING_AMOUNT,
           e.EAD_AMOUNT,
           p.ONE_YEAR_PD_RATE,
           p.LIFETIME_PD_RATE,
           l.LGD_RATE,
           l.RECOVERY_RATE,
           ROUND(
               e.EAD_AMOUNT
               * CASE WHEN s.STAGE_CODE = 'STAGE1' THEN p.ONE_YEAR_PD_RATE ELSE p.LIFETIME_PD_RATE END
               * l.LGD_RATE,
               2
           )
      FROM PRV_TARGET_CONTRACT t
      JOIN PRV_STAGE_RESULT s ON s.TARGET_ID = t.TARGET_ID
      JOIN PRV_EAD_RESULT e ON e.TARGET_ID = t.TARGET_ID
      JOIN PRV_PD_RESULT p ON p.TARGET_ID = t.TARGET_ID
      JOIN PRV_LGD_RESULT l ON l.TARGET_ID = t.TARGET_ID
     WHERE t.BATCH_EXECUTION_ID = p_batch_execution_id;
END;
/

CREATE OR REPLACE PROCEDURE PRC_PRV_INSERT_RESULT_SUMMARY (p_batch_execution_id IN NUMBER) IS
BEGIN
    INSERT INTO PRV_ECL_RESULT_SUMMARY (
        SUMMARY_ID, BATCH_EXECUTION_ID, BASE_DATE, PRODUCT_CODE, STAGE_CODE,
        CONTRACT_COUNT, TOTAL_CARRYING_AMOUNT, TOTAL_EAD_AMOUNT, TOTAL_ECL_AMOUNT, CREATED_AT
    )
    SELECT SQ_PRV_ECL_RESULT_SUMMARY.NEXTVAL,
           summary_rows.BATCH_EXECUTION_ID,
           summary_rows.BASE_DATE,
           summary_rows.PRODUCT_CODE,
           summary_rows.STAGE_CODE,
           summary_rows.CONTRACT_COUNT,
           summary_rows.TOTAL_CARRYING_AMOUNT,
           summary_rows.TOTAL_EAD_AMOUNT,
           summary_rows.TOTAL_ECL_AMOUNT,
           CURRENT_TIMESTAMP
      FROM (
            SELECT d.BATCH_EXECUTION_ID,
                   d.BASE_DATE,
                   d.PRODUCT_CODE,
                   d.STAGE_CODE,
                   COUNT(*) AS CONTRACT_COUNT,
                   SUM(d.CARRYING_AMOUNT) AS TOTAL_CARRYING_AMOUNT,
                   SUM(d.EAD_AMOUNT) AS TOTAL_EAD_AMOUNT,
                   SUM(d.ECL_AMOUNT) AS TOTAL_ECL_AMOUNT
              FROM PRV_ECL_RESULT_DTL d
             WHERE d.BATCH_EXECUTION_ID = p_batch_execution_id
             GROUP BY d.BATCH_EXECUTION_ID, d.BASE_DATE, d.PRODUCT_CODE, d.STAGE_CODE
      ) summary_rows;
END;
/

CREATE INDEX IX_CUSTOMER_RATING_01 ON CUSTOMER_RATING (CUSTOMER_ID, BASE_DATE);
CREATE INDEX IX_CUSTOMER_RATING_02 ON CUSTOMER_RATING (BASE_DATE, RATING_GRADE);
CREATE INDEX IX_LOAN_DELINQUENCY_01 ON LOAN_DELINQUENCY (CONTRACT_ID, BASE_DATE);
CREATE INDEX IX_LOAN_DELINQUENCY_02 ON LOAN_DELINQUENCY (BASE_DATE, DEFAULT_YN, DELINQUENCY_DAYS);
CREATE INDEX IX_LOAN_COLLATERAL_01 ON LOAN_COLLATERAL (CONTRACT_ID, BASE_DATE);
CREATE INDEX IX_LOAN_COLLATERAL_02 ON LOAN_COLLATERAL (BASE_DATE, COLLATERAL_TYPE);

CREATE INDEX IX_PRV_BATCH_EXEC_01 ON PRV_BATCH_EXECUTION (BASE_DATE, STATUS_CODE);
CREATE INDEX IX_PRV_BATCH_EXEC_02 ON PRV_BATCH_EXECUTION (BATCH_RUN_NO);
CREATE INDEX IX_PRV_STEP_EXEC_01 ON PRV_BATCH_STEP_EXECUTION (BATCH_EXECUTION_ID, STEP_NAME);
CREATE INDEX IX_PRV_TARGET_01 ON PRV_TARGET_CONTRACT (BATCH_EXECUTION_ID, CONTRACT_ID);
CREATE INDEX IX_PRV_TARGET_02 ON PRV_TARGET_CONTRACT (BASE_DATE, CONTRACT_NO);
CREATE INDEX IX_PRV_TARGET_03 ON PRV_TARGET_CONTRACT (BASE_DATE, PRODUCT_CODE, RATING_GRADE);
CREATE INDEX IX_PRV_STAGE_01 ON PRV_STAGE_RESULT (BATCH_EXECUTION_ID, TARGET_ID);
CREATE INDEX IX_PRV_STAGE_02 ON PRV_STAGE_RESULT (BATCH_EXECUTION_ID, CONTRACT_NO, STAGE_CODE);
CREATE INDEX IX_PRV_EAD_01 ON PRV_EAD_RESULT (BATCH_EXECUTION_ID, TARGET_ID);
CREATE INDEX IX_PRV_PD_01 ON PRV_PD_RESULT (BATCH_EXECUTION_ID, TARGET_ID);
CREATE INDEX IX_PRV_LGD_01 ON PRV_LGD_RESULT (BATCH_EXECUTION_ID, TARGET_ID);
CREATE INDEX IX_PRV_ECL_DTL_01 ON PRV_ECL_RESULT_DTL (BATCH_EXECUTION_ID, CONTRACT_NO);
CREATE INDEX IX_PRV_ECL_DTL_02 ON PRV_ECL_RESULT_DTL (BASE_DATE, PRODUCT_CODE, STAGE_CODE);
CREATE INDEX IX_PRV_ECL_SUM_01 ON PRV_ECL_RESULT_SUMMARY (BASE_DATE, PRODUCT_CODE, STAGE_CODE);
CREATE INDEX IX_PRV_ECL_SUM_02 ON PRV_ECL_RESULT_SUMMARY (BATCH_EXECUTION_ID);

COMMENT ON TABLE CUSTOMER_RATING IS '고객 등급 및 PD 원천';
COMMENT ON COLUMN CUSTOMER_RATING.RATING_ID IS '고객등급ID';
COMMENT ON COLUMN CUSTOMER_RATING.CUSTOMER_ID IS '고객ID';
COMMENT ON COLUMN CUSTOMER_RATING.BASE_DATE IS '기준일자';
COMMENT ON COLUMN CUSTOMER_RATING.RATING_GRADE IS '등급';
COMMENT ON COLUMN CUSTOMER_RATING.ONE_YEAR_PD_RATE IS '1년부도확률';
COMMENT ON COLUMN CUSTOMER_RATING.CREATED_AT IS '생성일시';
COMMENT ON COLUMN CUSTOMER_RATING.UPDATED_AT IS '수정일시';

COMMENT ON TABLE LOAN_DELINQUENCY IS '여신 연체 원천';
COMMENT ON COLUMN LOAN_DELINQUENCY.DELINQUENCY_ID IS '연체ID';
COMMENT ON COLUMN LOAN_DELINQUENCY.CONTRACT_ID IS '계약ID';
COMMENT ON COLUMN LOAN_DELINQUENCY.BASE_DATE IS '기준일자';
COMMENT ON COLUMN LOAN_DELINQUENCY.DELINQUENCY_DAYS IS '연체일수';
COMMENT ON COLUMN LOAN_DELINQUENCY.DEFAULT_YN IS '부도여부';
COMMENT ON COLUMN LOAN_DELINQUENCY.CREATED_AT IS '생성일시';
COMMENT ON COLUMN LOAN_DELINQUENCY.UPDATED_AT IS '수정일시';

COMMENT ON TABLE LOAN_COLLATERAL IS '여신 담보 및 회수율 원천';
COMMENT ON COLUMN LOAN_COLLATERAL.COLLATERAL_ID IS '담보ID';
COMMENT ON COLUMN LOAN_COLLATERAL.CONTRACT_ID IS '계약ID';
COMMENT ON COLUMN LOAN_COLLATERAL.BASE_DATE IS '기준일자';
COMMENT ON COLUMN LOAN_COLLATERAL.COLLATERAL_TYPE IS '담보유형';
COMMENT ON COLUMN LOAN_COLLATERAL.COLLATERAL_VALUE_AMT IS '담보가치금액';
COMMENT ON COLUMN LOAN_COLLATERAL.RECOVERY_RATE IS '회수율';
COMMENT ON COLUMN LOAN_COLLATERAL.CREATED_AT IS '생성일시';
COMMENT ON COLUMN LOAN_COLLATERAL.UPDATED_AT IS '수정일시';

COMMENT ON TABLE PRV_BATCH_EXECUTION IS '충당금 배치 실행 이력';
COMMENT ON COLUMN PRV_BATCH_EXECUTION.BATCH_EXECUTION_ID IS '배치실행ID';
COMMENT ON COLUMN PRV_BATCH_EXECUTION.BATCH_RUN_NO IS '배치실행번호';
COMMENT ON COLUMN PRV_BATCH_EXECUTION.BASE_DATE IS '기준일자';
COMMENT ON COLUMN PRV_BATCH_EXECUTION.BATCH_TYPE IS '배치유형';
COMMENT ON COLUMN PRV_BATCH_EXECUTION.STATUS_CODE IS '상태코드';
COMMENT ON COLUMN PRV_BATCH_EXECUTION.TARGET_COUNT IS '대상건수';
COMMENT ON COLUMN PRV_BATCH_EXECUTION.PROCESSED_COUNT IS '처리건수';
COMMENT ON COLUMN PRV_BATCH_EXECUTION.ERROR_COUNT IS '오류건수';
COMMENT ON COLUMN PRV_BATCH_EXECUTION.STARTED_AT IS '시작일시';
COMMENT ON COLUMN PRV_BATCH_EXECUTION.FINISHED_AT IS '종료일시';
COMMENT ON COLUMN PRV_BATCH_EXECUTION.ERROR_MESSAGE IS '오류메시지';

COMMENT ON TABLE PRV_BATCH_STEP_EXECUTION IS '충당금 배치 단계 실행 이력';
COMMENT ON COLUMN PRV_BATCH_STEP_EXECUTION.STEP_EXECUTION_ID IS '단계실행ID';
COMMENT ON COLUMN PRV_BATCH_STEP_EXECUTION.BATCH_EXECUTION_ID IS '배치실행ID';
COMMENT ON COLUMN PRV_BATCH_STEP_EXECUTION.STEP_NAME IS '단계명';
COMMENT ON COLUMN PRV_BATCH_STEP_EXECUTION.STATUS_CODE IS '상태코드';
COMMENT ON COLUMN PRV_BATCH_STEP_EXECUTION.STARTED_AT IS '시작일시';
COMMENT ON COLUMN PRV_BATCH_STEP_EXECUTION.FINISHED_AT IS '종료일시';
COMMENT ON COLUMN PRV_BATCH_STEP_EXECUTION.PROCESSED_COUNT IS '처리건수';
COMMENT ON COLUMN PRV_BATCH_STEP_EXECUTION.ERROR_MESSAGE IS '오류메시지';

COMMENT ON TABLE PRV_TARGET_CONTRACT IS '충당금 산출 대상 계약';
COMMENT ON COLUMN PRV_TARGET_CONTRACT.TARGET_ID IS '대상ID';
COMMENT ON COLUMN PRV_TARGET_CONTRACT.BATCH_EXECUTION_ID IS '배치실행ID';
COMMENT ON COLUMN PRV_TARGET_CONTRACT.BASE_DATE IS '기준일자';
COMMENT ON COLUMN PRV_TARGET_CONTRACT.CONTRACT_ID IS '계약ID';
COMMENT ON COLUMN PRV_TARGET_CONTRACT.CONTRACT_NO IS '계약번호';
COMMENT ON COLUMN PRV_TARGET_CONTRACT.CUSTOMER_ID IS '고객ID';
COMMENT ON COLUMN PRV_TARGET_CONTRACT.CUSTOMER_NAME IS '고객명';
COMMENT ON COLUMN PRV_TARGET_CONTRACT.PRODUCT_CODE IS '상품코드';
COMMENT ON COLUMN PRV_TARGET_CONTRACT.OUTSTANDING_PRINCIPAL_AMT IS '원금잔액금액';
COMMENT ON COLUMN PRV_TARGET_CONTRACT.CARRYING_AMOUNT IS '장부가금액';
COMMENT ON COLUMN PRV_TARGET_CONTRACT.DELINQUENCY_DAYS IS '연체일수';
COMMENT ON COLUMN PRV_TARGET_CONTRACT.DEFAULT_YN IS '부도여부';
COMMENT ON COLUMN PRV_TARGET_CONTRACT.RATING_GRADE IS '등급';
COMMENT ON COLUMN PRV_TARGET_CONTRACT.ONE_YEAR_PD_RATE IS '1년부도확률';
COMMENT ON COLUMN PRV_TARGET_CONTRACT.COLLATERAL_VALUE_AMT IS '담보가치금액';
COMMENT ON COLUMN PRV_TARGET_CONTRACT.RECOVERY_RATE IS '회수율';

COMMENT ON TABLE PRV_STAGE_RESULT IS '충당금 Stage 산출 결과';
COMMENT ON COLUMN PRV_STAGE_RESULT.STAGE_RESULT_ID IS 'Stage결과ID';
COMMENT ON COLUMN PRV_STAGE_RESULT.BATCH_EXECUTION_ID IS '배치실행ID';
COMMENT ON COLUMN PRV_STAGE_RESULT.TARGET_ID IS '대상ID';
COMMENT ON COLUMN PRV_STAGE_RESULT.CONTRACT_ID IS '계약ID';
COMMENT ON COLUMN PRV_STAGE_RESULT.CONTRACT_NO IS '계약번호';
COMMENT ON COLUMN PRV_STAGE_RESULT.STAGE_CODE IS 'Stage코드';
COMMENT ON COLUMN PRV_STAGE_RESULT.STAGE_REASON IS 'Stage판정사유';

COMMENT ON TABLE PRV_EAD_RESULT IS '충당금 EAD 산출 결과';
COMMENT ON COLUMN PRV_EAD_RESULT.EAD_RESULT_ID IS 'EAD결과ID';
COMMENT ON COLUMN PRV_EAD_RESULT.BATCH_EXECUTION_ID IS '배치실행ID';
COMMENT ON COLUMN PRV_EAD_RESULT.TARGET_ID IS '대상ID';
COMMENT ON COLUMN PRV_EAD_RESULT.CONTRACT_ID IS '계약ID';
COMMENT ON COLUMN PRV_EAD_RESULT.CONTRACT_NO IS '계약번호';
COMMENT ON COLUMN PRV_EAD_RESULT.CARRYING_AMOUNT IS '장부가금액';
COMMENT ON COLUMN PRV_EAD_RESULT.EAD_AMOUNT IS 'EAD금액';

COMMENT ON TABLE PRV_PD_RESULT IS '충당금 PD 산출 결과';
COMMENT ON COLUMN PRV_PD_RESULT.PD_RESULT_ID IS 'PD결과ID';
COMMENT ON COLUMN PRV_PD_RESULT.BATCH_EXECUTION_ID IS '배치실행ID';
COMMENT ON COLUMN PRV_PD_RESULT.TARGET_ID IS '대상ID';
COMMENT ON COLUMN PRV_PD_RESULT.CONTRACT_ID IS '계약ID';
COMMENT ON COLUMN PRV_PD_RESULT.CONTRACT_NO IS '계약번호';
COMMENT ON COLUMN PRV_PD_RESULT.STAGE_CODE IS 'Stage코드';
COMMENT ON COLUMN PRV_PD_RESULT.ONE_YEAR_PD_RATE IS '1년부도확률';
COMMENT ON COLUMN PRV_PD_RESULT.LIFETIME_PD_RATE IS '평생부도확률';

COMMENT ON TABLE PRV_LGD_RESULT IS '충당금 LGD 산출 결과';
COMMENT ON COLUMN PRV_LGD_RESULT.LGD_RESULT_ID IS 'LGD결과ID';
COMMENT ON COLUMN PRV_LGD_RESULT.BATCH_EXECUTION_ID IS '배치실행ID';
COMMENT ON COLUMN PRV_LGD_RESULT.TARGET_ID IS '대상ID';
COMMENT ON COLUMN PRV_LGD_RESULT.CONTRACT_ID IS '계약ID';
COMMENT ON COLUMN PRV_LGD_RESULT.CONTRACT_NO IS '계약번호';
COMMENT ON COLUMN PRV_LGD_RESULT.RECOVERY_RATE IS '회수율';
COMMENT ON COLUMN PRV_LGD_RESULT.LGD_RATE IS 'LGD율';

COMMENT ON TABLE PRV_ECL_RESULT_DTL IS '충당금 계약별 상세 결과';
COMMENT ON COLUMN PRV_ECL_RESULT_DTL.RESULT_DTL_ID IS '결과상세ID';
COMMENT ON COLUMN PRV_ECL_RESULT_DTL.BATCH_EXECUTION_ID IS '배치실행ID';
COMMENT ON COLUMN PRV_ECL_RESULT_DTL.BASE_DATE IS '기준일자';
COMMENT ON COLUMN PRV_ECL_RESULT_DTL.CONTRACT_ID IS '계약ID';
COMMENT ON COLUMN PRV_ECL_RESULT_DTL.CONTRACT_NO IS '계약번호';
COMMENT ON COLUMN PRV_ECL_RESULT_DTL.CUSTOMER_NAME IS '고객명';
COMMENT ON COLUMN PRV_ECL_RESULT_DTL.PRODUCT_CODE IS '상품코드';
COMMENT ON COLUMN PRV_ECL_RESULT_DTL.STAGE_CODE IS 'Stage코드';
COMMENT ON COLUMN PRV_ECL_RESULT_DTL.STAGE_REASON IS 'Stage판정사유';
COMMENT ON COLUMN PRV_ECL_RESULT_DTL.CARRYING_AMOUNT IS '장부가금액';
COMMENT ON COLUMN PRV_ECL_RESULT_DTL.EAD_AMOUNT IS 'EAD금액';
COMMENT ON COLUMN PRV_ECL_RESULT_DTL.ONE_YEAR_PD_RATE IS '1년부도확률';
COMMENT ON COLUMN PRV_ECL_RESULT_DTL.LIFETIME_PD_RATE IS '평생부도확률';
COMMENT ON COLUMN PRV_ECL_RESULT_DTL.LGD_RATE IS 'LGD율';
COMMENT ON COLUMN PRV_ECL_RESULT_DTL.RECOVERY_RATE IS '회수율';
COMMENT ON COLUMN PRV_ECL_RESULT_DTL.ECL_AMOUNT IS 'ECL금액';

COMMENT ON TABLE PRV_ECL_RESULT_SUMMARY IS '충당금 기준일자 요약 결과';
COMMENT ON COLUMN PRV_ECL_RESULT_SUMMARY.SUMMARY_ID IS '요약ID';
COMMENT ON COLUMN PRV_ECL_RESULT_SUMMARY.BATCH_EXECUTION_ID IS '배치실행ID';
COMMENT ON COLUMN PRV_ECL_RESULT_SUMMARY.BASE_DATE IS '기준일자';
COMMENT ON COLUMN PRV_ECL_RESULT_SUMMARY.PRODUCT_CODE IS '상품코드';
COMMENT ON COLUMN PRV_ECL_RESULT_SUMMARY.STAGE_CODE IS 'Stage코드';
COMMENT ON COLUMN PRV_ECL_RESULT_SUMMARY.CONTRACT_COUNT IS '계약건수';
COMMENT ON COLUMN PRV_ECL_RESULT_SUMMARY.TOTAL_CARRYING_AMOUNT IS '장부가합계금액';
COMMENT ON COLUMN PRV_ECL_RESULT_SUMMARY.TOTAL_EAD_AMOUNT IS 'EAD합계금액';
COMMENT ON COLUMN PRV_ECL_RESULT_SUMMARY.TOTAL_ECL_AMOUNT IS 'ECL합계금액';
COMMENT ON COLUMN PRV_ECL_RESULT_SUMMARY.CREATED_AT IS '생성일시';
