CREATE TABLE CUSTOMER_MASTER (
    CUSTOMER_ID BIGINT PRIMARY KEY,
    CUSTOMER_NO VARCHAR(30) NOT NULL UNIQUE,
    CUSTOMER_NAME VARCHAR(100) NOT NULL,
    CUSTOMER_TYPE VARCHAR(20) NOT NULL,
    SEGMENT_CODE VARCHAR(20),
    STATUS_CODE VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE LOAN_CONTRACT (
    CONTRACT_ID BIGINT PRIMARY KEY,
    CONTRACT_NO VARCHAR(30) NOT NULL UNIQUE,
    CUSTOMER_ID BIGINT NOT NULL,
    PRODUCT_CODE VARCHAR(30) NOT NULL,
    LOAN_TYPE_CODE VARCHAR(20) NOT NULL,
    REPAYMENT_TYPE VARCHAR(20) NOT NULL,
    EXECUTION_DATE DATE NOT NULL,
    MATURITY_DATE DATE NOT NULL,
    PRINCIPAL_AMT DECIMAL(18, 2) NOT NULL,
    FEE_AMT DECIMAL(18, 2) NOT NULL,
    DIRECT_COST_AMT DECIMAL(18, 2) NOT NULL,
    STATUS_CODE VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_LOAN_CONTRACT_01 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_MASTER (CUSTOMER_ID)
);

CREATE TABLE LOAN_RATE (
    RATE_ID BIGINT PRIMARY KEY,
    CONTRACT_ID BIGINT NOT NULL,
    RATE_TYPE VARCHAR(20) NOT NULL,
    ANNUAL_NOMINAL_RATE DECIMAL(18, 10) NOT NULL,
    EFFECTIVE_FROM DATE NOT NULL,
    EFFECTIVE_TO DATE,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_LOAN_RATE_01 FOREIGN KEY (CONTRACT_ID) REFERENCES LOAN_CONTRACT (CONTRACT_ID)
);

CREATE TABLE LOAN_REPAYMENT_SCHEDULE (
    SCHEDULE_ID BIGINT PRIMARY KEY,
    CONTRACT_ID BIGINT NOT NULL,
    INSTALLMENT_NO BIGINT NOT NULL,
    PAYMENT_DATE DATE NOT NULL,
    SCHEDULED_PAYMENT_AMT DECIMAL(18, 2) NOT NULL,
    SCHEDULED_PRINCIPAL_AMT DECIMAL(18, 2) NOT NULL,
    SCHEDULED_INTEREST_AMT DECIMAL(18, 2) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_LOAN_REPAYMENT_SCHEDULE_01 FOREIGN KEY (CONTRACT_ID) REFERENCES LOAN_CONTRACT (CONTRACT_ID)
);

CREATE TABLE LOAN_BALANCE (
    BALANCE_ID BIGINT PRIMARY KEY,
    CONTRACT_ID BIGINT NOT NULL,
    BASE_DATE DATE NOT NULL,
    OUTSTANDING_PRINCIPAL_AMT DECIMAL(18, 2) NOT NULL,
    ACCRUED_INTEREST_AMT DECIMAL(18, 2) NOT NULL,
    STATUS_CODE VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_LOAN_BALANCE_01 FOREIGN KEY (CONTRACT_ID) REFERENCES LOAN_CONTRACT (CONTRACT_ID)
);

CREATE TABLE CUSTOMER_RATING (
    RATING_ID BIGINT PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    BASE_DATE DATE NOT NULL,
    RATING_GRADE VARCHAR(20) NOT NULL,
    ONE_YEAR_PD_RATE DECIMAL(18, 10) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_CUSTOMER_RATING_01 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_MASTER (CUSTOMER_ID)
);

CREATE TABLE LOAN_DELINQUENCY (
    DELINQUENCY_ID BIGINT PRIMARY KEY,
    CONTRACT_ID BIGINT NOT NULL,
    BASE_DATE DATE NOT NULL,
    DELINQUENCY_DAYS BIGINT NOT NULL,
    DEFAULT_YN VARCHAR(1) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_LOAN_DELINQUENCY_01 FOREIGN KEY (CONTRACT_ID) REFERENCES LOAN_CONTRACT (CONTRACT_ID)
);

CREATE TABLE LOAN_COLLATERAL (
    COLLATERAL_ID BIGINT PRIMARY KEY,
    CONTRACT_ID BIGINT NOT NULL,
    BASE_DATE DATE NOT NULL,
    COLLATERAL_TYPE VARCHAR(30) NOT NULL,
    COLLATERAL_VALUE_AMT DECIMAL(18, 2) NOT NULL,
    RECOVERY_RATE DECIMAL(18, 10) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_LOAN_COLLATERAL_01 FOREIGN KEY (CONTRACT_ID) REFERENCES LOAN_CONTRACT (CONTRACT_ID)
);

CREATE TABLE LOCF_BATCH_EXECUTION (
    BATCH_EXECUTION_ID BIGINT PRIMARY KEY,
    BATCH_RUN_NO VARCHAR(40) NOT NULL UNIQUE,
    BASE_DATE DATE NOT NULL,
    BATCH_TYPE VARCHAR(20) NOT NULL,
    STATUS_CODE VARCHAR(20) NOT NULL,
    TARGET_COUNT BIGINT NOT NULL,
    PROCESSED_COUNT BIGINT NOT NULL,
    ERROR_COUNT BIGINT NOT NULL,
    STARTED_AT TIMESTAMP NOT NULL,
    FINISHED_AT TIMESTAMP,
    ERROR_MESSAGE VARCHAR(1000)
);

CREATE TABLE LOCF_BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID BIGINT PRIMARY KEY,
    BATCH_EXECUTION_ID BIGINT NOT NULL,
    STEP_NAME VARCHAR(50) NOT NULL,
    STATUS_CODE VARCHAR(20) NOT NULL,
    STARTED_AT TIMESTAMP NOT NULL,
    FINISHED_AT TIMESTAMP,
    PROCESSED_COUNT BIGINT NOT NULL,
    ERROR_MESSAGE VARCHAR(1000),
    CONSTRAINT FK_LOCF_STEP_EXEC_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES LOCF_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE LOCF_TARGET_CONTRACT (
    TARGET_ID BIGINT PRIMARY KEY,
    BATCH_EXECUTION_ID BIGINT NOT NULL,
    CONTRACT_ID BIGINT NOT NULL,
    CONTRACT_NO VARCHAR(30) NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    PRODUCT_CODE VARCHAR(30) NOT NULL,
    REPAYMENT_TYPE VARCHAR(20) NOT NULL,
    PRINCIPAL_AMT DECIMAL(18, 2) NOT NULL,
    FEE_AMT DECIMAL(18, 2) NOT NULL,
    DIRECT_COST_AMT DECIMAL(18, 2) NOT NULL,
    ANNUAL_NOMINAL_RATE DECIMAL(18, 10) NOT NULL,
    EXECUTION_DATE DATE NOT NULL,
    MATURITY_DATE DATE NOT NULL,
    TERM_IN_MONTHS BIGINT NOT NULL,
    CONSTRAINT FK_LOCF_TARGET_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES LOCF_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE LOCF_CASHFLOW_BASE (
    CASHFLOW_BASE_ID BIGINT PRIMARY KEY,
    BATCH_EXECUTION_ID BIGINT NOT NULL,
    CONTRACT_ID BIGINT NOT NULL,
    CONTRACT_NO VARCHAR(30) NOT NULL,
    INSTALLMENT_NO BIGINT NOT NULL,
    PAYMENT_DATE DATE NOT NULL,
    SCHEDULED_PAYMENT_AMT DECIMAL(18, 2) NOT NULL,
    SCHEDULED_PRINCIPAL_AMT DECIMAL(18, 2) NOT NULL,
    SCHEDULED_INTEREST_AMT DECIMAL(18, 2) NOT NULL,
    CONSTRAINT FK_LOCF_CF_BASE_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES LOCF_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE LOCF_EIR_RESULT (
    EIR_RESULT_ID BIGINT PRIMARY KEY,
    BATCH_EXECUTION_ID BIGINT NOT NULL,
    CONTRACT_ID BIGINT NOT NULL,
    CONTRACT_NO VARCHAR(30) NOT NULL,
    INITIAL_CARRYING_AMOUNT DECIMAL(18, 2) NOT NULL,
    MONTHLY_EIR DECIMAL(18, 10) NOT NULL,
    ANNUAL_EIR DECIMAL(18, 10) NOT NULL,
    CONSTRAINT FK_LOCF_EIR_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES LOCF_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE LOCF_AMORTIZATION_DTL (
    AMORTIZATION_DTL_ID BIGINT PRIMARY KEY,
    BATCH_EXECUTION_ID BIGINT NOT NULL,
    CONTRACT_ID BIGINT NOT NULL,
    CONTRACT_NO VARCHAR(30) NOT NULL,
    INSTALLMENT_NO BIGINT NOT NULL,
    PAYMENT_DATE DATE NOT NULL,
    OPENING_PRINCIPAL_BAL DECIMAL(18, 2) NOT NULL,
    OPENING_CARRYING_AMT DECIMAL(18, 2) NOT NULL,
    SCHEDULED_PAYMENT_AMT DECIMAL(18, 2) NOT NULL,
    SCHEDULED_PRINCIPAL_AMT DECIMAL(18, 2) NOT NULL,
    SCHEDULED_INTEREST_AMT DECIMAL(18, 2) NOT NULL,
    EFFECTIVE_INTEREST_REVENUE DECIMAL(18, 2) NOT NULL,
    FEE_AMORTIZATION_AMT DECIMAL(18, 2) NOT NULL,
    COST_AMORTIZATION_AMT DECIMAL(18, 2) NOT NULL,
    NET_AMORTIZATION_AMT DECIMAL(18, 2) NOT NULL,
    CLOSING_PRINCIPAL_BAL DECIMAL(18, 2) NOT NULL,
    CLOSING_CARRYING_AMT DECIMAL(18, 2) NOT NULL,
    CONSTRAINT FK_LOCF_AMORT_DTL_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES LOCF_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE LOCF_RESULT_HDR (
    RESULT_HDR_ID BIGINT PRIMARY KEY,
    BATCH_EXECUTION_ID BIGINT NOT NULL,
    BASE_DATE DATE NOT NULL,
    CONTRACT_ID BIGINT NOT NULL,
    CONTRACT_NO VARCHAR(30) NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    PRODUCT_CODE VARCHAR(30) NOT NULL,
    PRINCIPAL_AMT DECIMAL(18, 2) NOT NULL,
    INITIAL_CARRYING_AMOUNT DECIMAL(18, 2) NOT NULL,
    ANNUAL_EIR DECIMAL(18, 10) NOT NULL,
    FINAL_CARRYING_AMOUNT DECIMAL(18, 2) NOT NULL,
    TOTAL_EFFECTIVE_INTEREST_REV DECIMAL(18, 2) NOT NULL,
    TOTAL_FEE_AMORTIZATION_AMT DECIMAL(18, 2) NOT NULL,
    TOTAL_COST_AMORTIZATION_AMT DECIMAL(18, 2) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_LOCF_RESULT_HDR_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES LOCF_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE LOCF_RESULT_SUMMARY (
    SUMMARY_ID BIGINT PRIMARY KEY,
    BATCH_EXECUTION_ID BIGINT NOT NULL,
    BASE_DATE DATE NOT NULL,
    PRODUCT_CODE VARCHAR(30) NOT NULL,
    CONTRACT_COUNT BIGINT NOT NULL,
    TOTAL_INITIAL_CARRYING_AMT DECIMAL(18, 2) NOT NULL,
    TOTAL_FINAL_CARRYING_AMT DECIMAL(18, 2) NOT NULL,
    TOTAL_EFFECTIVE_INTEREST_REV DECIMAL(18, 2) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_LOCF_RESULT_SUM_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES LOCF_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE PRV_BATCH_EXECUTION (
    BATCH_EXECUTION_ID BIGINT PRIMARY KEY,
    BATCH_RUN_NO VARCHAR(40) NOT NULL UNIQUE,
    BASE_DATE DATE NOT NULL,
    BATCH_TYPE VARCHAR(20) NOT NULL,
    STATUS_CODE VARCHAR(20) NOT NULL,
    TARGET_COUNT BIGINT NOT NULL,
    PROCESSED_COUNT BIGINT NOT NULL,
    ERROR_COUNT BIGINT NOT NULL,
    STARTED_AT TIMESTAMP NOT NULL,
    FINISHED_AT TIMESTAMP,
    ERROR_MESSAGE VARCHAR(1000)
);

CREATE TABLE PRV_BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID BIGINT PRIMARY KEY,
    BATCH_EXECUTION_ID BIGINT NOT NULL,
    STEP_NAME VARCHAR(50) NOT NULL,
    STATUS_CODE VARCHAR(20) NOT NULL,
    STARTED_AT TIMESTAMP NOT NULL,
    FINISHED_AT TIMESTAMP,
    PROCESSED_COUNT BIGINT NOT NULL,
    ERROR_MESSAGE VARCHAR(1000),
    CONSTRAINT FK_PRV_STEP_EXEC_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES PRV_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE PRV_TARGET_CONTRACT (
    TARGET_ID BIGINT PRIMARY KEY,
    BATCH_EXECUTION_ID BIGINT NOT NULL,
    BASE_DATE DATE NOT NULL,
    CONTRACT_ID BIGINT NOT NULL,
    CONTRACT_NO VARCHAR(30) NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    CUSTOMER_NAME VARCHAR(100) NOT NULL,
    PRODUCT_CODE VARCHAR(30) NOT NULL,
    OUTSTANDING_PRINCIPAL_AMT DECIMAL(18, 2) NOT NULL,
    CARRYING_AMOUNT DECIMAL(18, 2) NOT NULL,
    DELINQUENCY_DAYS BIGINT NOT NULL,
    DEFAULT_YN VARCHAR(1) NOT NULL,
    RATING_GRADE VARCHAR(20) NOT NULL,
    ONE_YEAR_PD_RATE DECIMAL(18, 10) NOT NULL,
    COLLATERAL_VALUE_AMT DECIMAL(18, 2) NOT NULL,
    RECOVERY_RATE DECIMAL(18, 10) NOT NULL,
    CONSTRAINT FK_PRV_TARGET_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES PRV_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE PRV_STAGE_RESULT (
    STAGE_RESULT_ID BIGINT PRIMARY KEY,
    BATCH_EXECUTION_ID BIGINT NOT NULL,
    TARGET_ID BIGINT NOT NULL,
    CONTRACT_ID BIGINT NOT NULL,
    CONTRACT_NO VARCHAR(30) NOT NULL,
    STAGE_CODE VARCHAR(20) NOT NULL,
    STAGE_REASON VARCHAR(100) NOT NULL,
    CONSTRAINT FK_PRV_STAGE_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES PRV_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE PRV_EAD_RESULT (
    EAD_RESULT_ID BIGINT PRIMARY KEY,
    BATCH_EXECUTION_ID BIGINT NOT NULL,
    TARGET_ID BIGINT NOT NULL,
    CONTRACT_ID BIGINT NOT NULL,
    CONTRACT_NO VARCHAR(30) NOT NULL,
    CARRYING_AMOUNT DECIMAL(18, 2) NOT NULL,
    EAD_AMOUNT DECIMAL(18, 2) NOT NULL,
    CONSTRAINT FK_PRV_EAD_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES PRV_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE PRV_PD_RESULT (
    PD_RESULT_ID BIGINT PRIMARY KEY,
    BATCH_EXECUTION_ID BIGINT NOT NULL,
    TARGET_ID BIGINT NOT NULL,
    CONTRACT_ID BIGINT NOT NULL,
    CONTRACT_NO VARCHAR(30) NOT NULL,
    STAGE_CODE VARCHAR(20) NOT NULL,
    ONE_YEAR_PD_RATE DECIMAL(18, 10) NOT NULL,
    LIFETIME_PD_RATE DECIMAL(18, 10) NOT NULL,
    CONSTRAINT FK_PRV_PD_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES PRV_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE PRV_LGD_RESULT (
    LGD_RESULT_ID BIGINT PRIMARY KEY,
    BATCH_EXECUTION_ID BIGINT NOT NULL,
    TARGET_ID BIGINT NOT NULL,
    CONTRACT_ID BIGINT NOT NULL,
    CONTRACT_NO VARCHAR(30) NOT NULL,
    RECOVERY_RATE DECIMAL(18, 10) NOT NULL,
    LGD_RATE DECIMAL(18, 10) NOT NULL,
    CONSTRAINT FK_PRV_LGD_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES PRV_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE PRV_ECL_RESULT_DTL (
    RESULT_DTL_ID BIGINT PRIMARY KEY,
    BATCH_EXECUTION_ID BIGINT NOT NULL,
    BASE_DATE DATE NOT NULL,
    CONTRACT_ID BIGINT NOT NULL,
    CONTRACT_NO VARCHAR(30) NOT NULL,
    CUSTOMER_NAME VARCHAR(100) NOT NULL,
    PRODUCT_CODE VARCHAR(30) NOT NULL,
    STAGE_CODE VARCHAR(20) NOT NULL,
    STAGE_REASON VARCHAR(100) NOT NULL,
    CARRYING_AMOUNT DECIMAL(18, 2) NOT NULL,
    EAD_AMOUNT DECIMAL(18, 2) NOT NULL,
    ONE_YEAR_PD_RATE DECIMAL(18, 10) NOT NULL,
    LIFETIME_PD_RATE DECIMAL(18, 10) NOT NULL,
    LGD_RATE DECIMAL(18, 10) NOT NULL,
    RECOVERY_RATE DECIMAL(18, 10) NOT NULL,
    ECL_AMOUNT DECIMAL(18, 2) NOT NULL,
    CONSTRAINT FK_PRV_ECL_DTL_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES PRV_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE PRV_ECL_RESULT_SUMMARY (
    SUMMARY_ID BIGINT PRIMARY KEY,
    BATCH_EXECUTION_ID BIGINT NOT NULL,
    BASE_DATE DATE NOT NULL,
    PRODUCT_CODE VARCHAR(30) NOT NULL,
    STAGE_CODE VARCHAR(20) NOT NULL,
    CONTRACT_COUNT BIGINT NOT NULL,
    TOTAL_CARRYING_AMOUNT DECIMAL(18, 2) NOT NULL,
    TOTAL_EAD_AMOUNT DECIMAL(18, 2) NOT NULL,
    TOTAL_ECL_AMOUNT DECIMAL(18, 2) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_PRV_ECL_SUM_01 FOREIGN KEY (BATCH_EXECUTION_ID) REFERENCES PRV_BATCH_EXECUTION (BATCH_EXECUTION_ID)
);

CREATE TABLE PRV_INDIVIDUAL_EVAL_TARGET (
    INDIVIDUAL_TARGET_ID BIGINT PRIMARY KEY,
    BASE_DATE DATE NOT NULL,
    CONTRACT_ID BIGINT NOT NULL,
    CONTRACT_NO VARCHAR(30) NOT NULL,
    EVAL_REASON_CODE VARCHAR(30) NOT NULL,
    EVAL_REASON_DETAIL VARCHAR(500),
    RECOVERY_EXPECTED_AMT DECIMAL(18, 2),
    DISCOUNT_RATE DECIMAL(18, 10),
    ACTIVE_YN VARCHAR(1) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_PRV_IND_EVAL_01 FOREIGN KEY (CONTRACT_ID) REFERENCES LOAN_CONTRACT (CONTRACT_ID)
);

CREATE SEQUENCE SQ_CUSTOMER_MASTER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_LOAN_CONTRACT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_LOAN_RATE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_LOAN_REPAYMENT_SCHEDULE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_LOAN_BALANCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_CUSTOMER_RATING START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_LOAN_DELINQUENCY START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_LOAN_COLLATERAL START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_LOCF_BATCH_EXECUTION START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_LOCF_BATCH_STEP_EXECUTION START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_LOCF_TARGET_CONTRACT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_LOCF_CASHFLOW_BASE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_LOCF_EIR_RESULT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_LOCF_AMORTIZATION_DTL START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_LOCF_RESULT_HDR START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_LOCF_RESULT_SUMMARY START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_PRV_BATCH_EXECUTION START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_PRV_BATCH_STEP_EXECUTION START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_PRV_TARGET_CONTRACT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_PRV_STAGE_RESULT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_PRV_EAD_RESULT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_PRV_PD_RESULT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_PRV_LGD_RESULT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_PRV_ECL_RESULT_DTL START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_PRV_ECL_RESULT_SUMMARY START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_PRV_INDIVIDUAL_EVAL_TARGET START WITH 1 INCREMENT BY 1;

CREATE ALIAS PRC_LOCF_CLEAR_BATCH_DATA FOR "com.hi.locf.support.H2LocfProcedures.clearBatchData";
CREATE ALIAS PRC_LOCF_INSERT_TARGET_CONTRACTS FOR "com.hi.locf.support.H2LocfProcedures.insertTargetContracts";
CREATE ALIAS PRC_LOCF_INSERT_RESULT_SUMMARY FOR "com.hi.locf.support.H2LocfProcedures.insertResultSummary";
CREATE ALIAS PRC_PRV_CLEAR_BATCH_DATA FOR "com.hi.locf.support.H2LocfProcedures.clearProvisionBatchData";
CREATE ALIAS PRC_PRV_INSERT_TARGET_CONTRACTS FOR "com.hi.locf.support.H2LocfProcedures.insertProvisionTargetContracts";
CREATE ALIAS PRC_PRV_CALCULATE_STAGE FOR "com.hi.locf.support.H2LocfProcedures.calculateProvisionStage";
CREATE ALIAS PRC_PRV_CALCULATE_EAD FOR "com.hi.locf.support.H2LocfProcedures.calculateProvisionEad";
CREATE ALIAS PRC_PRV_CALCULATE_PD FOR "com.hi.locf.support.H2LocfProcedures.calculateProvisionPd";
CREATE ALIAS PRC_PRV_CALCULATE_LGD FOR "com.hi.locf.support.H2LocfProcedures.calculateProvisionLgd";
CREATE ALIAS PRC_PRV_CALCULATE_ECL FOR "com.hi.locf.support.H2LocfProcedures.calculateProvisionEcl";
CREATE ALIAS PRC_PRV_INSERT_RESULT_SUMMARY FOR "com.hi.locf.support.H2LocfProcedures.insertProvisionResultSummary";
